server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://192.168.9.223/security_authority
    username: root
    password: ablejava
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.able.oauthserver.doamin
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.able.oauthserver: debug